version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      maven-plugin:
        patterns:
          - "org.apache.maven.plugins:*"
      test-dependencies:
        patterns:
          - "org.junit.jupiter:*"
          - "org.mockito:*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        update-types:
          - "major"
        patterns:
          - "*"
