name: GriefPrevention
main: me.ryanhamshire.GriefPrevention.GriefPrevention
softdepend: [Vault, Multiverse-Core, My_Worlds, MystCraft, Transporter, WorldGuard, WorldEdit, RoyalCommands, MultiWorld, Denizen, CommandHelper, Iris]
dev-url: https://dev.bukkit.org/projects/grief-prevention
version: '${git.commit.id.describe}'
api-version: '1.21'
commands:
    xx:
      description: Switches the shovel tool to subdivision mode, used to subdivide your claims.
      usage: /<command>
      aliases: [sc, subdivideclaim]
      permission: griefprevention.claims
    restrictsubclaim:
      description: Restricts a subclaim, so that it inherits no permissions from the parent claim
      usage: /<command>
      aliases: rsc
      permission: griefprevention.claims
    setaccruedclaimblocks:
      description: Updates a player's accrued claim block total.
      usage: /<command> <player> <amount>
      permission: griefprevention.adjustclaimblocks
      aliases: scb
    deleteclaim:
      description: Deletes the claim you're standing in, even if it's not your claim.
      usage: /<command>
      permission: griefprevention.deleteclaims
    deleteallclaims:
      description: Deletes all of another player's claims.
      usage: /<command> <player>
      permission: griefprevention.deleteclaims
    deleteclaimsinworld:
      description: Deletes all the claims in a world.  Only usable at the server console.
      usage: /<command> <world>
      aliases: [deleteallclaimsinworld, clearclaimsinworld, clearallclaimsinworld]
      permission: griefprevention.deleteclaimsinworld
    deleteuserclaimsinworld:
      description: Deletes all the non-admin claims in a world.  Only usable at the server console.
      usage: /<command> <world>
      aliases: [deletealluserclaimsinworld, clearuserclaimsinworld, clearalluserclaimsinworld]
      permission: griefprevention.deleteclaimsinworld
    extendclaim:
      description: Resizes the land claim you're standing in by pushing or pulling its boundary in the direction you're facing.
      usage: /<command> <numberOfBlocks>
      aliases: [expandclaim, resizeclaim]
      permission: griefprevention.claims
    buyclaimblocks:
      description: Purchases additional claim blocks with server money.  Doesn't work on servers without a Vault-compatible economy plugin.
      usage: /<command> <numberOfBlocks>
      aliases: buyclaim
      permission: griefprevention.buysellclaimblocks
    sellclaimblocks:
      description: Sells your claim blocks for server money.  Doesn't work on servers without a Vault-compatible economy plugin.
      usage: /<command> <numberOfBlocks>
      aliases: sellclaim
      permission: griefprevention.buysellclaimblocks
    deletealladminclaims:
      description: Deletes all administrative claims.
      usage: /<command>
      permission: griefprevention.adminclaims
    adminclaimslist:
      description: Lists all administrative claims.
      usage: /<command>
      permission: griefprevention.adminclaims
    claimslist:
      description: Lists information about a player's claim blocks and claims.
      usage: /<command> or /<command> <player>
      aliases: [claimlist, listclaims]
      permission: griefprevention.claims
    claimexplosions:
      description: Toggles whether explosives may be used in a specific land claim.
      usage: /<command>
      permission: griefprevention.claims
      aliases: claimexplosion
    softmute:
      description: Toggles whether a player's messages will only reach other soft-muted players.
      usage: /<command> <player>
      permission: griefprevention.softmute
    ignoreplayer:
      description: Ignores another player's chat messages.
      usage: /<command> <player name>
      aliases: [ignore]
      permission: griefprevention.ignore
    unignoreplayer:
      description: Unignores another player's chat messages.
      usage: /<command> <player name>
      aliases: [unignore]
      permission: griefprevention.ignore
    ignoredplayerlist:
      description: Lists the players you're ignoring in chat.
      usage: /<command>
      aliases: [ignores, ignored, ignorelist, ignoredlist, listignores, listignored, ignoring]
      permission: griefprevention.ignore
    separate:
      description: Forces two players to ignore each other in chat.
      usage: /<command> <player1> <player2>
      permission: griefprevention.separate
    unseparate:
      description: Reverses /separate.
      usage: /<command> <player1> <player2>
      permission: griefprevention.separate

permissions:
    griefprevention.createclaims:
        description: Grants permission to create claims.
        default: true
    griefprevention.admin.*:
        description: Grants all administrative functionality.
        children:
            griefprevention.restorenature: true
            griefprevention.restorenatureaggressive: true
            griefprevention.ignoreclaims: true
            griefprevention.adminclaims: true
            griefprevention.name: true
            griefprevention.adjustclaimblocks: true
            griefprevention.deleteclaims: true
            griefprevention.spam: true
            griefprevention.lava: true
            griefprevention.eavesdrop: true
            griefprevention.deathblow: true
            griefprevention.softmute: true
            griefprevention.reload: true
            griefprevention.visualizenearbyclaims: true
            griefprevention.overrideclaimcountlimit: true
            griefprevention.transferclaim: true
            griefprevention.claimslistother: true
            griefprevention.siegeimmune: true
            griefprevention.separate: true
            griefprevention.eavesdropsigns: true
            griefprevention.claimbook: true
            griefprevention.notignorable: true
            griefprevention.seeinactivity: true
            griefprevention.eavesdropimmune: true
            griefprevention.deleteclaimsinworld: true
            griefprevention.siegeteleport: true
            griefprevention.unlockothersdrops: true
            griefprevention.seeclaimsize: true
    griefprevention.siegeimmune:
        description: Makes a player immune to /siege.
        default: op
    griefprevention.givepet:
        description: Grants permission to use /givepet.
        default: true
    griefprevention.siege:
        description: Grants permission to use /siege.
        default: true
    griefprevention.unlockdrops:
        description: Grants permission to use /unlockdrops.
        default: true
    griefprevention.unlockothersdrops:
        description: Grants permission to use /unlockdrops for other players.
        default: op
    griefprevention.trapped:
        description: Grants permission to use /trapped.
        default: true
    griefprevention.claimslistother:
        description: Grants permission to use /claimslist to get another player's information.
        default: op
    griefprevention.restorenature:
        description: Grants permission to use /restorenature.
        default: op
    griefprevention.transferclaim:
        description: Grants permission to use /transferclaim.
        default: op
    griefprevention.ignoreclaims:
        description: Grants permission to use /ignoreclaims.
        default: op
    griefprevention.adminclaims:
        description: Grants permission to create administrative claims.
        default: op
    griefprevention.deleteclaims:
        description: Grants permission to delete other players' claims.
        default: op
    griefprevention.adjustclaimblocks:
        description: Grants permission to add or remove bonus blocks from a player's account.
        default: op
    griefprevention.name:
        description: Grants permission to set a name on claims.
        default: true
    griefprevention.spam:
        description: Grants permission to log in, send messages, and send commands rapidly.
        default: op
    griefprevention.lava:
        description: Grants permission to place lava near the surface and outside of claims.
        default: op
    griefprevention.eavesdrop:
        description: Allows a player to see whispered chat messages (/tell) and softmuted messages.
        default: op
    griefprevention.eavesdropsigns:
        description: Allows a player to see sign placements as chat messages.
        default: op
    griefprevention.restorenatureaggressive:
        description: Grants access to /restorenatureaggressive and /restorenaturefill.
        default: op
    griefprevention.reload:
        description: Grants access to /gpreload.
        default: op
    griefprevention.softmute:
        description: Grants access to /softmute.
        default: op
    griefprevention.claims:
        description: Grants access to claim-related slash commands.
        default: true
    griefprevention.abandonallclaims:
        description: Grants access to /abandonallclaims.
        default: true
    griefprevention.buysellclaimblocks:
        description: Grants access to claim block buy/sell commands.
        default: true
    griefprevention.visualizenearbyclaims:
        description: Allows a player to see all nearby claims at once.
        default: op
    griefprevention.seeclaimsize:
        description: Allows a player to see claim size for other players claims when right clicking with investigation tool
        default: op
    griefprevention.overrideclaimcountlimit:
        description: Allows players to create more claims than the limit specified by the config.
        default: op
    griefprevention.separate:
        description: Grants access to /separate and /unseparate.
        default: op
    griefprevention.ignore:
        description: Grants access to /ignore, /unignore, and /ignorelist
        default: true
    griefprevention.claimbook:
        description: Grants access to /claimbook.
        default: op
    griefprevention.notignorable:
        description: Players with this permission can't be ignored.
        default: op
    griefprevention.seeinactivity:
        description: Players with this permission can see how long a claim owner has been offline.
        default: op
    griefprevention.eavesdropimmune:
        description: Players with this permission can't have their private messages eavesdropped.
        default: op
    griefprevention.siegeteleport:
        description: Players with this permission can teleport into and out of besieged areas.
        default: op
    griefprevention.premovementchat:
        description: Players with this permission can chat before moving.
        default: false
